# Generated by Django 4.2.6 on 2023-11-18 22:00

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="in_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="orders.order",
                verbose_name="Orders",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="listings.listing",
                verbose_name="Listing",
            ),
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="pictures",
            field=models.ManyToManyField(
                blank=True,
                to="listings.imagemodel",
                verbose_name="Manufacturer Pictures",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="categories",
            field=models.ManyToManyField(
                blank=True, to="listings.category", verbose_name="Listing Categories"
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="manufacturer",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="listings.manufacturer",
                verbose_name="Manufacturer",
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="applied_to",
            field=models.ManyToManyField(
                default=django.db.models.manager.BaseManager.all,
                to="listings.listing",
                verbose_name="Applied to",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="listings.category",
            ),
        ),
    ]
