# Generated by Django 4.2.6 on 2023-11-18 15:36

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Coupon Code')),
                ('discount', models.FloatField(verbose_name='Discount Amount')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Expiration Date')),
                ('applied_to', models.ManyToManyField(default=django.db.models.manager.BaseManager.all, to='listings.listing', verbose_name='Applied to')),
            ],
        ),
    ]
