# Generated by Django 4.2.6 on 2023-11-18 23:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="applied_to",
        ),
    ]
