# Generated by Django 4.2.6 on 2023-11-18 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_coupon'),
        ('listings', '0002_remove_product_is_customised_product_is_customized_and_more'),
    ]

    operations = [
    ]
