version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env

  redis:
    image: redis:latest
    restart: unless-stopped
    env_file:
      - ./backend/.env

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/modsecurity.conf:/etc/nginx/modsecurity.conf:ro
      - ./nginx/crs:/etc/nginx/crs:ro
    depends_on:
      - backend

volumes:
  postgres_data:
