# Generated by Django 4.2.6 on 2023-11-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magiclink",
            name="expires_at",
            field=models.DateTimeField(default="2023-11-19 00:09:11.449893"),
        ),
    ]
