# Generated by Django 4.2.6 on 2023-11-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_magiclink_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="is_staff",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="magiclink",
            name="expires_at",
            field=models.DateTimeField(default="2023-11-18 16:24:45.843830"),
        ),
    ]
