# Generated by Django 4.2.6 on 2023-11-18 15:54

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now=True, verbose_name="created at"),
        ),
        migrations.AddField(
            model_name="order",
            name="last_update",
            field=models.DateTimeField(auto_now=True, verbose_name="last update"),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_fee",
            field=models.FloatField(default=0.0, verbose_name="shipping fee"),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (1, "draft"),
                    (2, "paid"),
                    (3, "sent"),
                    (4, "cancelled"),
                    (5, "received"),
                ],
                default=1,
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_numbers",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=128),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
