# Generated by Django 4.2.6 on 2023-10-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_magiclink_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_superuser',
        ),
        migrations.AddField(
            model_name='client',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='magiclink',
            name='expires_at',
            field=models.DateTimeField(default='2023-10-15 15:00:57.152924'),
        ),
    ]
