# Generated by Django 4.2.6 on 2023-10-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_client_is_superuser_client_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='magiclink',
            name='expires_at',
            field=models.DateTimeField(default='2023-10-17 18:55:53.007393'),
        ),
    ]
