# Generated by Django 4.2.6 on 2023-11-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='type',
            field=models.CharField(choices=[('choices', 'Choices'), ('input', 'Input'), ('default', 'Default')], max_length=112, verbose_name='Characteristic Type'),
        ),
    ]
