# Generated by Django 4.2.6 on 2023-11-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_characteristic_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='additional_price',
            field=models.FloatField(default=0.0, verbose_name='Additional price for that variant'),
        ),
    ]
