# Generated by Django 4.2.6 on 2023-11-15 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_variant_additional_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='name',
            new_name='attr_name',
        ),
    ]
